import { GET_ALL_POSTS, GET_POST, GET_USER_POSTS } from '#src/modules/post/endpoints.js';
import {
    CREATE_TECHSERVICE,
    UPDATE_TECHSERVICE,
    DELETE_TECHSERVICE,
    GET_ALL_TECHSERVICES,
    GET_SPECIFIC_TECHSERVICE,
} from '#src/modules/tech-service/endpoints.js';

export default [
    CREATE_TECHSERVICE,
    UPDATE_TECHSERVICE,
    DELETE_TECHSERVICE,
    GET_ALL_TECHSERVICES,
    GET_SPECIFIC_TECHSERVICE,
    GET_ALL_POSTS,
    GET_USER_POSTS,
    GET_POST,
];
