const CREATE_SERVICE_ORDER = 'post:CREATE_SERVICE_ORDER';
const UPDATE_SERVICE_ORDER = 'post:UPDATE_SERVICE_ORDER';
const DELETE_SERVICE_ORDER = 'post:DELETE_SERVICE_ORDER';

export {
    CREATE_SERVICE_ORDER,
    UPDATE_SERVICE_ORDER,
    DELETE_SERVICE_ORDER
}