const CREATE_REVIEW = 'POST:CREATE_REVIEW';
const UPDATE_REVIEW = 'PATCH:UPDATE_REVIEW';
const DELETE_REVIEW = 'DELETE:DELETE_REVIEW';

export {
    CREATE_REVIEW,
    UPDATE_REVIEW,
    DELETE_REVIEW,
}