const CREATE_CATEGORY = 'category:CREATE_CATEGORY';
const UPDATE_CATEGORY = 'category:UPDATE_CATEGORY';
const GET_ALL_CATEGORYS = 'category:GET_ALL_CATEGORYS';
const GET_SPECIFIC_CATEGORY = 'category:GET_SPECIFIC_CATEGORY';
const DELETE_CATEGORY = 'category:DELETE_CATEGORY';

export {
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    GET_ALL_CATEGORYS,
    GET_SPECIFIC_CATEGORY,
    DELETE_CATEGORY,
};
