const CREATE_TECHSERVICE = 'techservice:CREATE_TECHSERVICE';
const UPDATE_TECHSERVICE = 'techservice:UPDATE_TECHSERVICE';
const GET_ALL_TECHSERVICES = 'techservice:GET_ALL_TECHSERVICES';
const GET_SPECIFIC_TECHSERVICE = 'techservice:GET_SPECIFIC_TECHSERVICE';
const DELETE_TECHSERVICE = 'techservice:DELETE_TECHSERVICE';

export {
    CREATE_TECHSERVICE,
    UPDATE_TECHSERVICE,
    GET_ALL_TECHSERVICES,
    GET_SPECIFIC_TECHSERVICE,
    DELETE_TECHSERVICE,
};
